### ISSUE TITLE
Error while testing

### ISSUE THREAD

**Issue by harshraj22** [codeclassroom/PlagCheck#3]
I am facing some error while testing it locally. What could be the possible reason ?

![Screenshot from 2019-10-27 10-23-26](https://user-images.githubusercontent.com/46635452/67629923-5ec7fb00-f8a4-11e9-9226-fd2aa10c6482.png)

**Comment by Bhupesh-V** [comment]
@harshraj22 did you change anything in `demo.py` ?

**Comment by harshraj22** [comment]
No, nothing changed

**Comment by Bhupesh-V** [comment]
ok @harshraj22 I will look onto this

**Comment by Bhupesh-V** [comment]
@harshraj22 you can test , it's fixed  now

**Comment by harshraj22** [comment]
Seems only first few lines of error message changed :cry: 

![Screenshot from 2019-11-02 14-43-26](https://user-images.githubusercontent.com/46635452/68068791-22ead500-fd7f-11e9-8b3c-77147f39c0ca.png)

**Comment by Bhupesh-V** [comment]
@harshraj22 
can you walk me with the process of what you did.
1. You got "Moss USER ID" from Moss.
2. Repo Cloned, installed requirements.
3. Made a `.env` file having the id.

**Comment by harshraj22** [comment]
and then ran demo.py as shown.

**Comment by Bhupesh-V** [comment]
Everything seems to work fine. I recently bundled it into a package .
Try installing plagcheck
`pip install plagcheck`

Can you tell me what Python version are you using?

**Comment by harshraj22** [comment]
I already installed that. Python 3.6.8
